refactor: switch to Rust
skyra-project/ai pull request #131
Opened 2022-05-11 01:10 UTC by kyranet

Pending to fix tests and write tests for Rust's side of things

2022-05-11 17:08 UTC, Nytelife26 requested changes
No further comments for now. Good work :)
I'll check more in-depth later.

2022-05-11 21:30 UTC, kyranet commented on src/games/connect_four.rs
> +	}
I don't have much of a clue of how can such thing be done, what do you suggest?

2022-05-11 21:35 UTC, kyranet commented on src/common/mod.rs
> +pub mod players;
Actually that's 1:1 with the C++ code, not TypeScript, but sure!

2022-05-11 22:04 UTC, Nytelife26 reviewed
After this and the macro for tidying up, I'll move to performance analysis. If you'd like to do some of your own in the meantime at the machine code level, I'd recommend using Godbolt.

2022-05-11 22:04 UTC, Nytelife26 commented on src/games/tic_tac_toe.rs
> +pub type AiBoard = [Players; BOARD_CELLS];
Given that there are many functions in this file that receive an `AiBoard` as their primary argument, it seems more idiomatic to define this as a unit struct (`pub struct AiBoard([Players; BOARD_CELLS]);`) and implement the receiving functions as methods.

2022-05-11 22:04 UTC, Nytelife26 commented on src/games/connect_four.rs
> +	}
I'll have to write up a prototype solution later.

2022-05-11 22:05 UTC, kyranet commented on src/lib.rs
> +pub const INVALID_INDEX: i64 = U_INVALID_INDEX as i64;
It doesn't, sadly.

And the code relies on INVALID_INDEX being an `usize`, since it's used for cell indexes, which are `usize`s as it's the type used in array indexes.

2022-05-11 22:05 UTC, kyranet commented on src/lib.rs
> +pub fn tic_tac_toe_handler(v: Uint8Array) -> Result<i64, Error> {
This is actually `napi::Error`.

2022-05-11 22:06 UTC, kyranet commented on src/games/tic_tac_toe.rs
> +pub type AiBoard = [Players; BOARD_CELLS];
Yeah, I plan on doing that once I 100% finish with Connect-Four.

2022-05-11 22:25 UTC, favna requested changes

2022-05-11 22:25 UTC, favna commented on .github/workflows/continuous-integration.yml
> +      - docs/**
Nice copypasta. Now sanitize the rest as well please.

2022-05-11 22:26 UTC, kyranet commented on .github/workflows/continuous-integration.yml
> +      - docs/**
Not copypasta, but autogenerated by napi-rs.

2022-05-11 22:35 UTC, favna requested changes
That'll be enough to go on with for now.

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +name: CI
Revert copypasta

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +    tags-ignore:
Revert copypasta

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +'on':
Revert copypasta (no quotes)

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +  MACOSX_DEPLOYMENT_TARGET: '10.13'
Add new lines between too level blocks

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +  pull_request: null
Remove the `null`

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +      - docs/**
Literally the same thing. Auto generated is nothing but copying over a template.

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +      - uses: actions/checkout@v3
Revert

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +          check-latest: true
Remove this line, it's default not necessary.

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +          architecture: ${{ matrix.settings.architecture }}
Will default to system architecture so this line should be unnecessary I think

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +      - name: Cache NPM dependencies
Remove step, build into setup-node

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +    needs:
needs: build

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +        settings:
Remove this settings nonsense and just use matrix.os like a sane workflow would

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +    needs:
needs: build

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +        node:
node: [16, 18]

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +        node:
node: [16, 18]

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +      - test-linux-x64-musl-binding
```suggestion
    needs: [test-macOS-windows-binding, test-linux-x64-gnu-binding, test-linux-x64-musl-binding]
```

2022-05-11 22:35 UTC, favna commented on .github/workflows/continuous-integration.yml
> +          check-latest: true
```suggestion
```

2022-05-11 23:39 UTC, Nytelife26 commented
Since `Player` implements `PartialEq`, you can replace the redundant compare functions in each module with this more idiomatic solution that can be stored in `src/lib.rs`.

This will also work for any other type that implements `PartialEq`, and is loosely variadic in the sense that it can receive any slice of up to `usize` elements.

```
#[inline(always)]
pub fn many_eq<T: PartialEq>(conjuncts: &[T]) -> bool {
    conjuncts.windows(2).all(|x| x[0] == x[1])
}
```

2022-05-16 07:11 UTC, Nytelife26 reviewed
I equally dislike myself for not mentioning this sooner. Although, fortunately, it's probably the easiest change I've pointed out.

2022-05-16 07:11 UTC, Nytelife26 commented on index.d.ts
> +export const enum Players {
Minor detail I forgot to mention, but this should be named `Player`. It's standard practice to name enumerated sets as though each of their constituents are a *variant* of the set.

It may also be more efficient to use `Option<Player>` instead of `Player::Unset`.

2022-05-16 07:34 UTC, kyranet commented on index.d.ts
> +export const enum Players {
No, it isn't. It requires checking for the existence when I can just check the value.

Not to mention it also uses more memory, which is a red flag for heavy simulations.

2022-05-17 00:16 UTC, Nytelife26 commented on src/games/connect_four.rs
> +		self.remaining[column] != 0
This is more of a stylistic choice, but it seems more natural to say that `x > 0` for an unsigned integer than `x != 0`. They are semantically the same in this context, but I think `x > 0` captures the meaning better.

Much like how you'd likely just write `x > 0` for unsigned 8-bit integers in a mathematical sense instead of the following:

![formula](https://latex.codecogs.com/png.image?%5Cinline%20%5Clarge%20%5Cdpi%7B200%7D%5Cbg%7Bwhite%7D%5C%7Bx%5Cin%5Cmathbb%7BZ%7D%5E&plus;:0%3Cx%3C256%5C%7D)

2022-05-17 00:16 UTC, Nytelife26 commented on src/games/connect_four.rs
> +			let offset = self.piece_offset(c);
You could replace this with `(0..BOARD_WIDTH).filter_map`, but I'm not sure how much it'd like the move semantics for the mutable reference to `self`.

2022-05-17 00:16 UTC, Nytelife26 commented on src/games/tic_tac_toe.rs
> +			6 | 7 | 8 => many_eq!(self.cells[6], self.cells[7], self.cells[8]),
Another stylistic note, these can all be written in the inclusive range format `0..=2 => many_eq!(...)`.

2022-05-17 17:05 UTC, kyranet commented on package.json
> +		"fmt:rust": "cargo fmt",
That would require everyone developing this library to have the nightly version, when the stable version is more encouraged to use.

2022-05-17 17:05 UTC, kyranet commented on src/games/connect_four.rs
> +		const I_BOARD_WIDTH: isize = BOARD_WIDTH as isize;
It's done that way for readability, but I suppose I could change this function to what TTT does.

2022-05-17 17:06 UTC, kyranet commented on src/games/connect_four.rs
> +			let offset = self.piece_offset(c);
I also considered it, but it was less readable.

2022-05-17 17:06 UTC, kyranet commented on src/games/tic_tac_toe.rs
> +			6 | 7 | 8 => many_eq!(self.cells[6], self.cells[7], self.cells[8]),
This is intentional, it's meant to show the board's cells.

2022-05-17 19:39 UTC, Nytelife26 commented on src/games/connect_four.rs
> +		napi_assert!(self.remaining[c] != 0);
You may have forgotten to update this to be `> 0` too.

2022-05-17 19:45 UTC, Nytelife26 approved these changes
LGTM after that final nitpick.

2022-06-01 21:30 UTC, favna requested changes
Barring this I have no idea about the production code but I trust Nyte reviewed that. I also have no idea how to version and publish it so that will be on your shoulders.

2022-06-01 21:30 UTC, favna commented on .github/workflows/continuous-integration.yml
> +    if: "!contains(github.event.head_commit.message, 'skip ci')"
```suggestion
```

This is automatic, specifically with `[skip ci]`

I so told you about the whole template thing

2022-06-01 21:30 UTC, favna commented on .github/workflows/continuous-integration.yml
> +          architecture: ${{ matrix.settings.architecture }}
Resolved without reply

2022-06-01 21:30 UTC, favna commented on .github/workflows/continuous-integration.yml
> +        settings:
Resolved without resolution. This still applies.

2022-06-01 21:30 UTC, favna commented on .gitignore
> +*.tgz
```suggestion
```

We don't use npm nor do we run pack

2022-06-01 21:30 UTC, favna commented on .gitignore
> +.node_repl_history
```suggestion
```

We don't use Node REPL and also this file is written to `~/` in modern Node, not the current directory

2022-06-01 21:30 UTC, favna commented on .gitignore
> +.eslintcache
```suggestion
```

We have no eslint cache

2022-06-01 21:30 UTC, favna commented on .gitignore
> +
```suggestion
```

We don't use npm

2022-06-01 21:30 UTC, favna commented on index.cjs
> +	// For Node 10
10? You can drop support for 10.

2022-06-01 21:30 UTC, favna commented on npm/linux-x64-musl/package.json
> +	"version": "1.2.0",
These versions really should be 2.0.0 with this rewrite and standard-version or similar aren't going to be bumping them automatically.

2022-06-01 21:30 UTC, favna commented on package.json
> +		"fmt:node": "prettier --write .github npm tests index.cjs index.mjs index.d.ts",
```suggestion
		"fmt:node": "prettier --write \".github npm tests index.cjs index.mjs index.d.ts\"",
```

2022-06-01 21:30 UTC, favna commented on package.json
> +		"test:node-lint": "eslint tests/**/*.mjs",
```suggestion
		"test:node-lint": "eslint \"tests/**/*.mjs\"",
```

2022-06-01 21:30 UTC, favna commented on package.json
> +		"fmt:rust": "cargo fmt",
unresolved

2022-06-01 21:30 UTC, favna commented on package.json
> +		"prepublishOnly": "napi prepublish -t npm",
```suggestion
		"prepack": "napi prepublish -t npm && pinst --disable",
```

2022-06-01 21:30 UTC, favna commented on package.json
> +		"prepare": "husky install .github/husky",
```suggestion
		"postinstall": "husky install .github/husky",
		"postpack": "pinst --enable"
```

2022-06-01 21:30 UTC, favna commented on package.json
> +	"optionalDependencies": {},
```suggestion
```

2022-06-01 21:33 UTC, kyranet commented on index.cjs
> +	// For Node 10
Can't, that file is auto-generated.

2022-06-01 21:34 UTC, kyranet commented on package.json
> +		"fmt:node": "prettier --write .github npm tests index.cjs index.mjs index.d.ts",
Are those needed? `fmt:node` works as-is

2022-06-01 21:47 UTC, favna commented on index.cjs
> +	// For Node 10
Oh

2022-06-01 21:49 UTC, favna commented on package.json
> +		"fmt:node": "prettier --write .github npm tests index.cjs index.mjs index.d.ts",
Without the files will be globbed by the terminal which can differ on a user to user basis, whereas with they are globbed by prettier (internally using fast-glob)

2022-06-01 21:49 UTC, favna commented on npm/linux-x64-musl/package.json
> +	"version": "1.2.0",
Uhhhhh if you say so. Honestly you're going to have to handle releases as mentioned.

2022-06-01 21:51 UTC, favna commented on src/games/connect_four.rs
> +			let offset = self.piece_offset(c);
Unresolved

2022-06-01 21:51 UTC, favna commented on src/games/tic_tac_toe.rs
> +			6 | 7 | 8 => many_eq!(self.cells[6], self.cells[7], self.cells[8]),
Unresolved

2022-06-01 21:51 UTC, kyranet commented on Cargo.toml
> +# harness = false
Yeah, @Nytelife26 wants to do a benchmark suite at a later time, when he gets time for it.

2022-06-01 21:53 UTC, kyranet commented on src/games/tic_tac_toe.rs
> +			6 | 7 | 8 => many_eq!(self.cells[6], self.cells[7], self.cells[8]),
This is intentional. And Nyte has approved all the style changes.

2022-06-01 21:59 UTC, kyranet commented on .github/workflows/continuous-integration.yml
> +        settings:
But then I wouldn't be able to define the target, which is a very valid thing.

`macos-latest` builds `x86_64-apple-darwin`, and `windows-latest` builds `x86_64-pc-windows-msvc`.

2022-09-08 02:03 UTC, Nytelife26 commented
Status on this?

2022-09-08 03:19 UTC, kyranet commented
There are TODOs left to do before merging, and I'm sadly too busy for that at the moment :/

2022-09-08 15:05 UTC, Nytelife26 commented
> There are TODOs left to do before merging, and I'm sadly too busy for that at the moment :/

If there's anything you want me to do, let me know. I'm moving into student accommodation soon so I'll be mostly free until the 23rd.

2024-04-16 09:09 UTC, merged