refactor(connect-four): add board evaluation
skyra-project/ai pull request #228
Opened 2024-05-12 00:40 UTC by kyranet

Implemented the heuristics to evaluate the board using as reference:

- https://medium.com/analytics-vidhya/artificial-intelligence-at-play-connect-four-minimax-algorithm-explained-3b5fc32e4a4f
- https://github.com/KeithGalli/Connect4-Python/blob/master/connect4_with_ai.py
- https://roboticsproject.readthedocs.io/en/latest/ConnectFourAlgorithm.html

However, I'm not quite happy with the performance, so I will try to see if I can improve it.

2024-05-13 15:56 UTC, Nytelife26 requested changes

2024-05-13 15:56 UTC, Nytelife26 commented on src/games/connect_four.rs
> +			.map_windows(|window: &[usize; 4]| self.evaluate_window(player, window[0], window[1], window[2], window[3]))
since `evaluate_window` is only used once (here), it may be better to change its signature for simplicity

2024-05-13 15:56 UTC, Nytelife26 commented on src/games/connect_four.rs
> +		];
since constants of this structure are created several times throughout the code, we should probably find a way to reduce the boilerplate here

2024-05-13 15:56 UTC, Nytelife26 commented on src/games/connect_four.rs
> +		}
these can be moved up a level since they're all the same and reused

2024-05-13 15:56 UTC, Nytelife26 commented on src/lib.rs
> +}
in the below `TryFrom` implementation, it is assumed that the representation of a `Player` is `u8`. transmuting an unsigned representation to a signed one (especially when internal enum discriminants are not guaranteed across systems) may lead to surprising results.

i would therefore recommend, as `Player` is a linear populated enum (therefore cyclic and sized), standardising these to `usize` and casting when needed.

2024-05-13 16:03 UTC, kyranet commented on src/games/connect_four.rs
> +		_ => unsafe { unreachable_unchecked() },
It had instruction analysis:
<details>
<summary>With `unreachable_unchecked()` (6 instructions)</summary>

```asm
; fn bitmask_to_count(mask: Mask<i8, 4>) -> u8 {
     movd    xmm0, dword, ptr, [rcx]
     pmovmskb eax, xmm0
; match mask.to_bitmask() {
 movzx   eax, al
 lea     rcx, [rip, +, switch.table._ZN8skyra_ai5games12connect_four16bitmask_to_count17h49140c22359dd8aeE]
 movzx   eax, byte, ptr, [rax, +, rcx]
; }
 ret
```

```rust
fn bitmask_to_count(mask: Mask<i8, 4>) -> u8 {
	match mask.to_bitmask() {
		0b0000 => 0,
		0b0001 | 0b0010 | 0b0100 | 0b1000 => 1,
		0b0011 | 0b0101 | 0b0110 | 0b1001 | 0b1010 | 0b1100 => 2,
		0b0111 | 0b1011 | 0b1101 | 0b1110 => 3,
		0b1111 => 4,
		_ => unsafe { unreachable_unchecked() },
	}
}
```

</details>

<details>
<summary>Without `unreachable_unchecked()` (9 instructions)</summary>

```asm
; fn bitmask_to_count(mask: Mask<i8, 4>) -> u8 {
     movd    xmm0, dword, ptr, [rcx]
     pmovmskb ecx, xmm0
     mov     al, 4
; match mask.to_bitmask() {
 cmp     cl, 14
 ja      .LBB38_2
 movzx   eax, cl
 lea     rcx, [rip, +, switch.table._ZN8skyra_ai5games12connect_four16bitmask_to_count17h49140c22359dd8aeE]
 movzx   eax, byte, ptr, [rax, +, rcx]
.LBB38_2:
; }
 ret
```

```rust
fn bitmask_to_count(mask: Mask<i8, 4>) -> u8 {
	match mask.to_bitmask() {
		0b0000 => 0,
		0b0001 | 0b0010 | 0b0100 | 0b1000 => 1,
		0b0011 | 0b0101 | 0b0110 | 0b1001 | 0b1010 | 0b1100 => 2,
		0b0111 | 0b1011 | 0b1101 | 0b1110 => 3,
		_ => 4,
	}
}
```

</details>

My assumption is that it seems to force Rust to understand that the range of valid bits is any between 0b0000 and 0b1111, which allows it to do calculations on 4 bits rather than having to handle a lot more cases.

2024-05-13 16:08 UTC, kyranet commented on src/games/connect_four.rs
> +		}
Not 100% the same, line 1294 here is different to the rest. I gotta admit they look very similar though, I'm open for suggestions (or a macro that reduces this to less lines).

2024-05-13 16:11 UTC, kyranet commented on src/games/connect_four.rs
> +			.map_windows(|window: &[usize; 4]| self.evaluate_window(player, window[0], window[1], window[2], window[3]))
I iterated over this method many many times (more than I'd like to admit), I could for starters make it pass the array rather than passing the 4 values.

That asides, what signature do you suggest?

2024-05-13 17:44 UTC, Nytelife26 commented on src/games/connect_four.rs
> +		}
you can relocate `score_x` into a macro token, like `$score:ident`, to make it generic.

2024-05-13 17:49 UTC, Nytelife26 commented on src/games/connect_four.rs
> +			.map_windows(|window: &[usize; 4]| self.evaluate_window(player, window[0], window[1], window[2], window[3]))
i would pass the array, like you mentioned. you could also make it return a partial function (think "currying"), so it would slot in directly.

2024-05-13 18:36 UTC, Nytelife26 commented on src/lib.rs
> +}
that makes sense, i suppose. feel free to resolve this.

2024-05-13 19:01 UTC, kyranet commented on src/games/connect_four.rs
> +		];
I agree, that's like my least favourite part to see, but they're also critical for the performance of this app.

What I can do, however, is define all the constants for all coordinates (used in the `check_x` methods) and expand them, then I can do for this case:
```rust
const POSITIONS: [usize; BOARD_HEIGHT] = [0, B1, B2, B3, B4, B5];
```

It'll still have the boilerplate, but it'll be less visually noisy, and will also reduce the amount of lines of code.

2024-05-13 19:02 UTC, kyranet commented on src/games/connect_four.rs
> +		}
Right, I didn't even think of this, thanks!

2024-05-13 20:49 UTC, Nytelife26 commented on src/games/connect_four.rs
> +}
just noticed something i didn't earlier. this can be replaced with `u64::count_ones` (which uses intrinsics::ctpop internally, and is highly performant).
```suggestion
#[inline(always)]
fn bitmask_to_count(mask: Mask<i8, 4>) -> u8 {
	mask.to_bitmask().count_ones()
```

2024-05-13 22:01 UTC, Nytelife26 commented on src/games/connect_four.rs
> +		let v = i8x4::from_array(i.map(|x| unsafe { (*self.cells.get_unchecked(x)).try_into().unwrap_unchecked() }));
```suggestion
		let v = i8x4::from_array(i.map(|x| unsafe { *self.cells.get_unchecked(x) }.into()));
```

2024-05-13 22:08 UTC, Nytelife26 commented on src/games/connect_four.rs
> +			0b100_000 => unsafe { unreachable_unchecked() },
use octal to make these more readable, like this
```suggestion
			0o4_0 => unsafe { unreachable_unchecked() },
```

2024-05-13 22:11 UTC, kyranet commented on src/games/connect_four.rs
> +}
That's what I had originally, but it uses too many instructions.

```asm
; fn bitmask_to_count(mask: Mask<i8, 4>) -> u8 {
     movd    xmm0, dword, ptr, [rcx]
     pmovmskb ecx, xmm0
     mov     eax, ecx
     shr     al
     and     al, 85
     sub     cl, al
     mov     eax, ecx
     and     al, 51
     shr     cl, 2
     and     cl, 51
     add     cl, al
     mov     eax, ecx
     shr     al, 4
     add     al, cl
     and     al, 15
; }
 ret
```

The current code is much smaller and avoids using the same registry variable in many consecutive instructions:
```asm
; fn bitmask_to_count(mask: Mask<i8, 4>) -> u8 {
     movd    xmm0, dword, ptr, [rcx]
     pmovmskb eax, xmm0
; match mask.to_bitmask() {
 movzx   eax, al
 lea     rcx, [rip, +, switch.table._ZN8skyra_ai5games12connect_four16bitmask_to_count17h49140c22359dd8aeE]
 movzx   eax, byte, ptr, [rax, +, rcx]
; }
 ret
```

2024-05-13 22:15 UTC, Nytelife26 commented on src/games/connect_four.rs
> +}
that's strange. well, feel free to resolve. we should probably add comments to these explaining why they are how they are, so future onlookers don't have the same questions

2024-05-13 22:33 UTC, Nytelife26 commented on src/games/connect_four.rs
> +		];
a generic constructor for each entry would be
```rs
base + BOARD_WIDTH * idx + if additive { idx } else { 0 }
```
but i am not sure how you would implement this without inducing some kind of loss in performance.

2024-05-13 22:34 UTC, kyranet commented on src/games/connect_four.rs
> +			0b100_000 => unsafe { unreachable_unchecked() },
You saviour, I was kinda "darn, I wish 3-bit literals were a thing" and never occurred to me that octals are literally that 😅

2024-05-13 22:37 UTC, kyranet commented on src/games/connect_four.rs
> +		];
Update: I can't, `B1`, `B2`, and `B3` from `check` are `isize` (because negative ranges), and this uses strictly `usize`.

It'd also declare a lot of unused code in the top-level with this change, which is not desirable.

2024-05-13 22:38 UTC, kyranet commented on src/games/connect_four.rs
> +}
Done in d611caf

2024-05-13 22:48 UTC, Nytelife26 commented on src/games/connect_four.rs
> +			// - 3 empty pieces (0 opponent pieces)
it would be better to have a single comment block at the top of the match describing what the values mean than all of this scattered everywhere, in my opinion

2024-05-13 22:48 UTC, Nytelife26 commented on src/games/connect_four.rs
> +		];
i will work on a macro (or if i can think of something better, i'll do that instead) for this

i am, however, noticing that each of these functions has a lot of boilerplate, so if i'm going to go to those lengths i might consider making one that generates the entire thing

2024-05-13 23:06 UTC, kyranet commented on src/games/connect_four.rs
> +			// - 3 empty pieces (0 opponent pieces)
tbf the scattered documentation made me aware of the `0o02 => -10` case, which I'd otherwise not have noticed.

If you can think of a way that makes a mask's encoding clear while keeping this readable (and preferably grouped), I'm open to suggestions

2024-05-14 00:04 UTC, Nytelife26 commented on src/games/connect_four.rs
> +	}
```suggestion
		// each mask is comprised of two octal values, representing the player pieces and empty pieces respectively
		// since the player, empty and opponent pieces must sum to 4, these are the only fields required
		// for example, if there are no player pieces, and 1 empty piece, there must be 3 opponent pieces
		// this is how scoring is determined
		let mask: u8 = (player_pieces << 3) | empty_pieces;
		match mask {
			// 4 player pieces: (winning move, cannot happen here)
			0o4_0 => unsafe { unreachable_unchecked() },

			// 3 player pieces:
			0o3_1 => 100,
			0o3_0 => 0,

			// 2 player pieces:
			0o2_2 => 10,
			0o2_1 | 0o2_0 => 0,

			// 1 player piece:
			0o1_0..=0o1_3 => 0,

			// 0 player pieces:
			// - 0 empty pieces (losing move, cannot happen here)
			0o0_0 => unsafe { unreachable_unchecked() },
			0o0_1 => -100,
			0o0_2 => -10,
			0o0_3 | 0o0_4 => 0,

			// This should never happen:
			_ => unsafe { unreachable_unchecked() },
		}
	}
```

2024-05-14 00:11 UTC, Nytelife26 commented on src/lib.rs
> +		unsafe { transmute(value) }
myself and most other sources (like the [rust docs](https://doc.rust-lang.org/std/mem/fn.transmute.html) refer to `std::mem::transmute` explicitly, instead of importing it, to prevent confusion.

it may also be worth looking at `transmute_copy`, or even `transmute_unchecked`, if you want to demolish even more of the guard rails.

2024-05-20 19:20 UTC, Nytelife26 approved these changes
i have nothing left to add that wouldn't simply be nitpicking, like `make_` and `generate_` can both be `gen_` by convention. looks good :)

2024-05-20 19:40 UTC, merged