feat: add unit tests in C++
skyra-project/ai pull request #26
Opened 2021-04-10 11:50 UTC by Stitch07

2021-04-10 17:22 UTC, Tylertron1998 commented on test.cc
> +    std::cout << "Hello world!\n";
why is this here?

2021-04-10 17:24 UTC, Stitch07 commented on test.cc
> +    std::cout << "Hello world!\n";
whoops

2021-04-10 17:46 UTC, kyranet requested changes

2021-04-10 17:46 UTC, kyranet commented on binding.gyp
> +      ],
Does it need googletest in the production build?

2021-04-10 17:46 UTC, kyranet commented on tests/Connect4.cc
> +}
```suggestion
	connect_four::ai_board b{};
	EXPECT_EQ(connect_four::position(b, 42, 5), 3);
}
```

2021-04-11 09:15 UTC, Stitch07 commented on binding.gyp
> +      ],
Resolved in b70c2b0

2021-04-11 17:24 UTC, kyranet approved these changes

2021-04-11 17:25 UTC, merged